# Generated by Django 6.1 on 2026-08-17 21:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kitchen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_fund', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('OPEN', 'Abierta'), ('CLOSED', 'Cerrada'), ('SQUARED', 'Cuadrada'), ('UNRECONCILED', 'Descuadre Pendiente')], default='OPEN', max_length=16)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('declared_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('difference', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('justification', models.TextField(blank=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_registers', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_registers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas (turnos)',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=180)),
                ('client_cedula', models.CharField(blank=True, max_length=16)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_rate', models.DecimalField(decimal_places=4, default='0.15', max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(choices=[('FULL', 'Pago completo'), ('PARTIAL', 'Pago parcial')], default='FULL', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('ISSUED', 'Emitida'), ('ANNULLED', 'Anulada')], default='DRAFT', max_length=16)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('annulled_at', models.DateTimeField(blank=True, null=True)),
                ('annulled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='annulled_invoices', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='kitchen.order')),
                ('register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='billing.cashregister')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-issued_at'],
            },
        ),
    ]
