# Generated by Django 6.1 on 2026-08-17 21:21

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_rate', models.DecimalField(decimal_places=4, default='0.15', max_digits=5)),
                ('operating_timezone', models.CharField(default='America/Panama', max_length=64)),
                ('operating_start', models.TimeField(default='10:00')),
                ('operating_end', models.TimeField(default='00:00')),
                ('min_reservation_hours', models.IntegerField(default=12)),
                ('table_block_minutes', models.IntegerField(default=2)),
                ('no_show_grace_minutes', models.IntegerField(default=15)),
                ('cash_tolerance', models.DecimalField(decimal_places=2, default='2.00', max_digits=8)),
                ('pin_ttl_seconds', models.IntegerField(default=60)),
                ('loyalty_valid_months', models.IntegerField(default=3)),
                ('points_per_dollar', models.IntegerField(default=1)),
                ('redeem_points_per_dollar', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Configuración de negocio',
                'verbose_name_plural': 'Configuración de negocio',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('CASHIER', 'Cajero'), ('WAITER', 'Mesero'), ('CHEF', 'Chef'), ('WAREHOUSE', 'Encargado de Bodega'), ('CLIENT', 'Cliente')], default='WAITER', max_length=16)),
                ('cedula', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('failed_login_count', models.IntegerField(default=0)),
                ('suspended_until', models.DateTimeField(blank=True, null=True)),
                ('is_permanently_locked', models.BooleanField(default=False)),
                ('username', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
