# Generated by Django 6.1 on 2026-08-17 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_cedula', models.CharField(db_index=True, max_length=16)),
                ('movement_type', models.CharField(choices=[('ACCRUAL', 'Acreditación'), ('REDEMPTION', 'Canje'), ('EXPIRY', 'Caducidad')], max_length=12)),
                ('points', models.IntegerField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('client_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de puntos',
                'verbose_name_plural': 'Movimientos de fidelización',
                'ordering': ['-created_at'],
            },
        ),
    ]
