# Generated by Django 6.1 on 2026-08-17 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('capacity', models.PositiveIntegerField(choices=[(2, '2'), (4, '4'), (6, '6'), (12, '12')])),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('shape', models.CharField(default='circle', max_length=16)),
                ('is_contiguous_group', models.CharField(blank=True, max_length=255)),
                ('disabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_email', models.EmailField(max_length=254)),
                ('client_cedula', models.CharField(max_length=16)),
                ('guests', models.PositiveIntegerField(default=1)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('RESERVED', 'Reservada'), ('CONFIRMED', 'Confirmada'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada'), ('NO_SHOW', 'Cancelada por no-show')], default='RESERVED', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancel_notice_hours', models.IntegerField(default=0)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('tables', models.ManyToManyField(related_name='reservations', to='reservations.table')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='TableBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('confirmed', models.BooleanField(default=False)),
                ('tables', models.ManyToManyField(related_name='active_blocks', to='reservations.table')),
            ],
            options={
                'verbose_name': 'Bloqueo de mesa',
                'verbose_name_plural': 'Bloqueos de mesa',
            },
        ),
    ]
