# Generated by Django 6.1 on 2026-08-26 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='room',
            field=models.CharField(choices=[('VIP', 'Sala VIP'), ('TERRAZA', 'Terraza'), ('PISO_1', 'Piso 1')], default='PISO_1', max_length=16, verbose_name='Sala'),
        ),
        migrations.AlterField(
            model_name='table',
            name='x',
            field=models.FloatField(default=0, help_text='Coordenada X (0-100) para plano visual'),
        ),
        migrations.AlterField(
            model_name='table',
            name='y',
            field=models.FloatField(default=0, help_text='Coordenada Y (0-100) para plano visual'),
        ),
    ]
