# Generated by Django 6.1 on 2026-08-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGIN_FAILED', 'Login fallido'), ('LOGOUT', 'Logout'), ('ANULATION', 'Anulación de factura'), ('SHRINKAGE', 'Merma'), ('CASH_CLOSE', 'Cierre de caja'), ('CASH_OPEN', 'Apertura de caja'), ('PIN_ISSUE', 'Emisión de PIN'), ('PIN_CONSUMED', 'PIN consumido'), ('INVENTORY_CORRECTION', 'Corrección de inventario'), ('RESERVATION', 'Reserva'), ('RESERVATION_CANCEL', 'Cancelación de reserva'), ('CHECK_IN', 'Check-in'), ('NO_SHOW', 'No-show')], max_length=32)),
                ('result', models.CharField(choices=[('SUCCESS', 'Éxito'), ('FAILURE', 'Fallo')], default='SUCCESS', max_length=16)),
                ('object_type', models.CharField(blank=True, max_length=64)),
                ('object_id', models.CharField(blank=True, max_length=255)),
                ('detail', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Bitácora de auditoría',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PinToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'verbose_name': 'Token PIN',
                'verbose_name_plural': 'Tokens PIN',
            },
        ),
    ]
