# Generated by Django 6.1 on 2026-08-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGIN_FAILED', 'Login fallido'), ('LOGOUT', 'Logout'), ('ANULATION', 'Anulación de factura'), ('SHRINKAGE', 'Merma'), ('CASH_CLOSE', 'Cierre de caja'), ('CASH_OPEN', 'Apertura de caja'), ('INVOICE_ISSUE', 'Emisión de factura'), ('PIN_ISSUE', 'Emisión de PIN'), ('PIN_CONSUMED', 'PIN consumido'), ('INVENTORY_CORRECTION', 'Corrección de inventario'), ('RESERVATION', 'Reserva'), ('RESERVATION_CANCEL', 'Cancelación de reserva'), ('CHECK_IN', 'Check-in'), ('NO_SHOW', 'No-show')], max_length=32),
        ),
    ]
