# Generated by Django 6.1 on 2026-08-17 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.CharField(default='ACTIVE', max_length=24)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Platillo',
                'verbose_name_plural': 'Platillos',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WAITING', 'En Espera'), ('PREPARING', 'En Preparación'), ('READY', 'Listo'), ('DELIVERED', 'Entregado'), ('CANCELLED', 'Cancelada')], default='WAITING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='reservations.table')),
                ('waiter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taken_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comanda',
                'verbose_name_plural': 'Comandas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('cancelled_reason', models.CharField(blank=True, max_length=255)),
                ('replacement_requested', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kitchen.order')),
            ],
            options={
                'verbose_name': 'Ítem de comanda',
                'verbose_name_plural': 'Ítems de comanda',
            },
        ),
        migrations.CreateModel(
            name='Shrinkage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('notify_waiter_replacement', models.BooleanField(default=False)),
                ('replaced_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='shrinkage', to='kitchen.orderitem')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shrinkages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Merma',
                'verbose_name_plural': 'Mermas',
            },
        ),
    ]
