# Generated by Django 6.1 on 2026-08-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='description',
            field=models.CharField(blank=True, help_text='Descripción corta para el menú cliente.', max_length=255),
        ),
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen del platillo para el menú cliente (recomendado 800x600, JPG/PNG, máx 2MB).', null=True, upload_to='dishes/'),
        ),
    ]
