# Generated by Django 6.1 on 2026-08-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_add_image_to_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image_data',
            field=models.TextField(blank=True, default='', help_text='Data URL base64 de la imagen (fallback si S3/filesystem no disponible).'),
        ),
    ]
